language: python

cache: pip

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"

matrix:
    allow_failures:
        - python: "nightly"

install:
    - ./build_install.sh

script: 
    - python tests/my-calc.py add 1 2

after_script:
    - bash <(curl -s https://codecov.io/bash)
